book store commit
misha-levko/book-store-spring pull request #3
Opened 2024-06-23 23:52 UTC by misha-levko

book store first commit

2024-06-24 05:19 UTC, Elena-Bruyako requested changes
Please, provide main class with implementation according to the task

2024-06-24 05:19 UTC, Elena-Bruyako commented on book-store-spring/src/main/java/mate/academy/bookstorespring/model/Book.java
> +@Data
```suggestion
@Getter
@Setter
@Table(name = "books")
```

Annotation Data could cause some issues, try to avoid using it for Entities

2024-07-02 06:54 UTC, Elena-Bruyako requested changes
see comments

2024-07-02 06:54 UTC, Elena-Bruyako commented on book-store-spring/src/main/java/mate/academy/bookstorespring/repository/BookDaoImpl.java
> +            throw new RuntimeException("Can't insert book into DB: " + book);
```suggestion
            throw new DataProcessingException("Can't insert book into DB: " + book);
```

2024-07-02 06:54 UTC, Elena-Bruyako commented on book-store-spring/src/main/java/mate/academy/bookstorespring/repository/BookDaoImpl.java
> +            throw new RuntimeException("Can't get all books from DB");
```suggestion
            throw new DataProcessingException("Can't get all books from DB");
```

2024-07-03 06:19 UTC, Elena-Bruyako requested changes
see pr

2024-07-03 06:19 UTC, Elena-Bruyako commented on book-store-spring/src/main/java/mate/academy/bookstorespring/repository/BookDaoImpl.java
> +public class BookDaoImpl implements BookRepository {
```suggestion
public class BookRepositoryImpl implements BookRepository {
```

2024-07-03 06:19 UTC, Elena-Bruyako commented on book-store-spring/pom.xml
> +            <artifactId>commons-dbcp2</artifactId>
why do you need this dependency?

2024-07-03 06:19 UTC, Elena-Bruyako commented on book-store-spring/pom.xml
> +            <artifactId>spring-security-test</artifactId>
the same

2024-07-03 06:19 UTC, Elena-Bruyako commented on book-store-spring/pom.xml
> +            <artifactId>spring-boot-docker-compose</artifactId>
?

2024-07-04 06:30 UTC, Elena-Bruyako requested changes
see pr

2024-07-04 06:30 UTC, Elena-Bruyako commented on book-store-spring/pom.xml
> +            <artifactId>spring-boot-devtools</artifactId>
remove unnecessary dependency

2024-07-04 06:30 UTC, Elena-Bruyako commented on book-store-spring/pom.xml
> +            <artifactId>spring-boot-docker-compose</artifactId>
remove unnecessary dependency

2024-07-04 06:30 UTC, Elena-Bruyako commented on book-store-spring/pom.xml
> +            <artifactId>spring-boot-configuration-processor</artifactId>
remove unnecessary dependency

2024-07-11 12:04 UTC, Elena-Bruyako approved these changes
well done

2024-07-28 16:28 UTC, MentorMateAcademy requested changes

2024-07-28 16:28 UTC, MentorMateAcademy commented on book-store-spring/src/main/java/mate/academy/bookstorespring/repository/BookRepositoryImpl.java
> +        try (EntityManager entityManager = entityManagerFactory.createEntityManager()) {
try with resources use for read processes

2024-07-28 16:28 UTC, MentorMateAcademy commented on book-store-spring/src/main/java/mate/academy/bookstorespring/repository/BookRepositoryImpl.java
> +            throw e;
why do you trow in catch?

2024-08-02 14:02 UTC, okuzan approved these changes

2024-09-05 12:52 UTC, Elena-Bruyako requested changes
<img width="997" alt="Screenshot 2024-09-05 at 15 50 43" src="https://github.com/user-attachments/assets/9930901b-f4a2-4b93-a4dc-55fc7f00d805">
Changes was approved, provide new PR

2024-09-07 13:48 UTC, merged