Book store spring Part 3
misha-levko/book-store-spring pull request #4
Opened 2024-09-07 13:56 UTC by misha-levko

Added Liquibase support; implemented the soft delete concept.

2024-09-08 15:13 UTC, Elena-Bruyako requested changes
next time mentor reject your HW without any checking, if there will be several HWs

2024-09-08 15:13 UTC, Elena-Bruyako commented on book-store-spring/src/main/java/mate/academy/bookstorespring/BookStoreSpringApplication.java
> +@SpringBootApplication(scanBasePackages = "mate.academy.bookstorespring")
```suggestion
@SpringBootApplication
```

2024-09-08 15:13 UTC, Elena-Bruyako commented on book-store-spring/src/main/java/mate/academy/bookstorespring/controller/BookController.java
> +@RequestMapping(value = "/books")
```suggestion
@RequestMapping("/books")
```

2024-09-08 15:13 UTC, Elena-Bruyako commented on book-store-spring/src/main/java/mate/academy/bookstorespring/controller/BookController.java
> +    public BookDto createBook(@RequestBody CreateBookRequestDto bookDto) {
why these changes in this PR? they should be done in previous HW. After mentor approved your HW you should merge it to master and create new branch and make HW. Otherwise, mentor will reject your PR

2024-09-08 15:13 UTC, Elena-Bruyako commented on book-store-spring/src/main/java/mate/academy/bookstorespring/repository/BookRepository.java
> +
```suggestion
```

2024-09-08 15:13 UTC, Elena-Bruyako commented on book-store-spring/src/main/java/mate/academy/bookstorespring/service/BookServiceImpl.java
> +        bookUpdate.setTitle(bookDto.getTitle());
use mapstruct for these logic

2024-09-08 15:13 UTC, Elena-Bruyako commented on book-store-spring/src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:testdb
h2 is used for test purposes, create mysql db according to the task description

2024-10-14 18:41 UTC, closed without merging

2024-10-14 18:42 UTC, misha-levko commented
closed