added Liquibase support; implemented the soft delete concept.
misha-levko/book-store-spring pull request #5
Opened 2024-09-16 01:03 UTC by misha-levko

Added Endpoints to BookController

2024-09-16 12:05 UTC, Elena-Bruyako requested changes
Task not completed

You need to implement: 
Change spring.jpa.hibernate.ddl-auto property value to validate
Implement soft delete concept for the Book entity

2024-09-16 12:05 UTC, Elena-Bruyako commented on book-store-spring/src/main/java/mate/academy/bookstorespring/service/BookServiceImpl.java
> +        bookRepository.findById(id).orElseThrow(() ->
```suggestion
        Book book = bookRepository.findById(id).orElseThrow(() ->
```

2024-09-16 12:05 UTC, Elena-Bruyako commented on book-store-spring/src/main/java/mate/academy/bookstorespring/service/BookServiceImpl.java
> +        Book updatedBook = bookRepository.save(book);
```suggestion
        bookMapper.updateBookFromDto(bookRequestDto, book);
        return bookMapper.toDto(bookRepository.save(book));
```

2024-09-16 12:05 UTC, Elena-Bruyako commented on book-store-spring/src/main/java/mate/academy/bookstorespring/repository/BookRepository.java
>      Optional<Book> getBookById(Long id);
```suggestion
```

2024-09-17 17:04 UTC, Elena-Bruyako requested changes
didn't find liquibase changelogs in your implementation

2024-09-18 10:28 UTC, MentorMateAcademy approved these changes

2024-10-14 18:39 UTC, merged